@startuml
actor AN as "Analyst"
left to right direction

usecase "Generate Country Report \n[[Country_Breakdowns.md]]" as UC1
usecase "Generate City Report" as UC2
usecase "Generate Capital City Report" as UC3
usecase "Generate Population Breakdown Report \n[[Population-Breakdowns.md]]" as UC4
usecase "Generate Basic Population Report" as UC5
usecase "Generate Language Report" as UC6

AN --> UC1
AN --> UC2
AN --> UC3
AN --> UC4
AN --> UC5
AN --> UC6
}
@enduml