@startuml
actor "Data Analyst" as Analyst

rectangle "Population Reporting System" {
  usecase "Produce Population Breakdown by Continent" as UC23
  usecase "Produce Population Breakdown by Region" as UC24
  usecase "Produce Population Breakdown by Country" as UC25

}

Analyst --> UC23
Analyst --> UC24
Analyst --> UC25
@enduml
