@startuml
actor "Data Analyst" as Analyst

rectangle "Population Reporting System" {
  usecase "Produce Population Breakdown by Continent" as UC23
  usecase "Produce Population Breakdown by Region" as UC24
  usecase "Produce Population Breakdown by Country" as UC25

  usecase "Retrieve population data" as UC_R
  usecase "Calculate urban vs non-urban %" as UC_C
  usecase "Generate formatted report" as UC_G

}

Analyst --> UC23
Analyst --> UC24
Analyst --> UC25
@enduml
